# permissions for end users to edit configmapsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: my-first-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: configmapsync-editor-role
rules:
- apiGroups:
  - apps.xirehat.com
  resources:
  - configmapsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.xirehat.com
  resources:
  - configmapsyncs/status
  verbs:
  - get
